FROM node:20-alpine

WORKDIR /app

# Install dependencies
# COPY frontend/package*.json ./
# RUN npm install

# Copy project files
# COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
